holidays/definitions

ca.yaml

from https://en.wikipedia.org/wiki/Provinces_and_territories_of_Canada

Fixed Canadian province/territory codes

---

de.yaml

see details https://github.com/holidays/definitions/issues/15

fix typo de_yaml

---

kr.yaml

- Korean New Year is 3 days
- Use Korean language
BTW, How can I run test in `kr.yaml` file?
I tried `bundle exec rspec`, `make validate`.
But, It seems not works.

Update Korean holiday

---

fr.yaml

* Add additional holidays for Alsace (fr_a) and Moselle (fr_m)
* Enhance tests

Enhance French holiday definitions

---

pt.yaml

* Add additional holidays for Porto (pt_po) and Lisbon (pt_li)
* Enhance tests

Enhance Portuguese holiday definitions

---

index.yaml
ru.yaml

* Russian holidays in Cyrillic language
* Tests are included

Add Russian holiday definitions

---

index.yaml
tr.yaml

* Add static national holidays
* Add Ramadan Feast and Sacrifice Feast holidays
* Includes functions for Ramadan/Sacrifice Feast with pre-defined dates from 2014 to 2019
* Includes tests

Add Turkish holiday definitions

---

ge.yaml
index.yaml

- Holiday definitions in Georgian language (based on Mchedruli alphabet)
- Tests are included

Add Georgian holiday definitions

---

tr.yaml

as [Wikipedia Link](https://en.wikipedia.org/wiki/Democracy_and_National_Unity_Day) shows July 15 is declared as national holiday

Add July 15

---

federal_reserve.yaml

This PR will move holidays that fall on Saturday to Friday.
This should fix issue: https://github.com/holidays/holidays/issues/274

federal_reserve.yaml: fix Saturday holidays

---

CONTRIBUTING.md

Addresses https://github.com/holidays/definitions/issues/94

[Issue-94] Fix link to CoC in CONTRIBUTING doc

---

.travis.yml

Addresses https://github.com/holidays/definitions/issues/97

[issue-97] Remove ruby 2.2 and add 2.5 to travis builds

---

gb.yaml

This was opened to address https://github.com/holidays/holidays/issues/310.

Modify gb_nir for St. Patricks Day to observe on Monday if weekend

---

ca.yaml

Tests for https://github.com/holidays/definitions/pull/115

Add tests for Civic Holiday (Terry Fox Day) for ca_mb

---

es.yaml

https://es.wikipedia.org/wiki/Fiesta_de_San_Juan

Add San Juan to Catalunya and Comunidad Valenciana holidays

---

hu.yaml

I added tests, but when I tried to run them by `make test`, it reported the same number of examples as upstream - so chances are my tests were not actually run; if you can run the tests and they fail, please advise on how to run the tests correctly.

HU: Friday before Easter is official since 2017

---

hr.yaml

Law on holidays, public holidays and non-working days in the Republic of Croatia
https://www.zakon.hr/z/372/Zakon-o-blagdanima,-spomendanima-i-neradanim-danima-u-Republici-Hrvatskoj

New Croatian holidays 2020

---

ca.yaml

See detail https://github.com/holidays/definitions/pull/156#issuecomment-613642837

'Nunavut Day' should be active from 2020.

---

ch.yaml

・Delete unnecessary 'end'.
・Correct comments.

Fix ch holidays.

---

si.yaml

Source: https://publicholidays.eu/slovenia/sl/2022-dates/

Update new year's eve in si.yml

---

nyse.yaml

Add Juneteenth to NYSE calendar

---

gb.yaml

Add QEII Memorial Bank Holiday

---

fr.yaml

Hello
It's the whit monday who's informal not the ascension day (see on wikipedia : Monday after Pentecost (50 days after Easter), observed only in some businesses).
thanks

french informal whit monday

---

de.yaml

Source: https://de.wikipedia.org/wiki/Tag_der_Deutschen_Einheit#Bundesrepublik_Deutschland

Historical data for Tag der Deutschen Einheit

---

index.yaml

Partially addressing https://github.com/holidays/definitions/issues/217#issuecomment-1875122081
Needed to add KE to index.yaml file

Ensure Kenya is included

---

lt.yaml

Added November 2nd to LT holidays list
