holidays/definitions

- jp.yaml
The exact name will contain the word "の".
see:
- [Wikipedia](https://en.wikipedia.org/wiki/National_Foundation_Day)
- [government link](http://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html#hourutsu)
> Fix National Foundation Day name of japanese

- ca.yaml
Hello! This PR adds the observed days Canadian national holidays. It seems that the general rule for Canada is to always observe the holidays on the following Monday if the actual holiday falls on the weekend. If Christmas falls on a weekend, it is observed on Monday and Boxing day is observed on Tuesday.
Sources:
- http://www.bankofcanada.ca/about/contact-information/bank-of-canada-holiday-schedule/. 
- http://www.tpsgc-pwgsc.gc.ca/remuneration-compensation/paye-centre-pay/feries-holidays-eng.html
@ptrimble for review
> Add observed days for canadian national holidays

- au.yaml
With the current Australian holiday definitions, there is no country wide default for Christmas or Boxing day. You need to specify the state even though Christmas and Boxing Day are national holidays, even if the rules if when they are observed are slightly different.
Currently if I run `Holidays.on(Date.civil(2016, 12, 25), :au)` I get empty array back. The goal of this PR is to add `au` to the definition used by most Australian states.
Source: http://www.australia.gov.au/about-australia/special-dates-and-events/public-holidays
@ptrimble
> Add defaults for Christmas and Boxing day for AU

- ie.yaml
This method is unnecessary since it is an exact replication of `to_weekday_if_boxing_weekend`.
@ptrimble
> IE yaml file slight refactor

- de.yaml
used car license plate abbreviations to reflect the regions where a
holiday is celebrated
Sorry, this doesn't fix the problem with missing holidays on de_by_a AKA de_by_aux, I'm still investigating.
> changes de yml to better reflect regions

- au.yaml
- de.yaml
- ph.yaml
Australia: Vic & NT have changed how christmas related holidays are defined, see https://nt.gov.au/employ/for-employees-in-nt/nt-public-holidays http://www.gazette.vic.gov.au/gazette/Gazettes2016/GG2016S364.pdf http://www.business.vic.gov.au/victorian-public-holidays-and-daylight-saving/victorian-public-holidays
Australia: Fix AFL grand final bug raised at https://github.com/holidays/holidays/issues/252#issuecomment-267761775
Philippines: convert some dates that are "special days" to `informal`, my understanding is that these are days in which not everyone works but are not formally treated as public holidays. see http://www.gov.ph/2015/08/20/proclamation-no-1105-s-2015/
Germany: fix a typo in a test
> Updates for AU & Philippines holidays

- nyse.yaml
NYSE observes the following Monday if the New Year's Day falls on a Sunday.
This is what happened on January 2017: the observed date was Monday, January 2nd
References:
https://www.nyse.com/markets/hours-calendars
http://nyserules.nyse.com/nyse/rules/nyse-rules/chp_1_3/chp_1_3_3/default.asp
Signed-off-by: Vassilios Liatsos <vassilis@tradelegs.com>
> Fix observed New Year's day for NYSE

- au.yaml
See https://github.com/holidays/definitions/pull/31 for more information on why we want to revert.
@ghiculescu @adamlyons2 Can you please verify that this looks good to you?
> Fix au NYD defs

- kr.yaml
- vi.yaml
Following our discussion on #28, I've updated the `lunar_date` calculations and added a Vietnam specific hash.  This PR uses that new hash.
> Add region specification to lunar_to_solar call

- au.yaml
Hey @ghiculescu and @adamlyons2. Unfortunately I have more bad news here. What I've discovered is that everything is working as intended, except...for this in the ruby repo: https://github.com/holidays/holidays/blob/master/lib/holidays/finder/rules/in_region.rb#L9-L21
Basically, when we determine whether a specific date is 'in a region' we also currently check its parent region. By adding back in `:au` we are telling `:au_tas` to also grab any `:au` holidays, which means it ALSO picks up the NYD from 1/1. This isn't what you wanted but...I don't see an easy fix for the moment.
The problem is that there are a lot of other tests/features that rely on this functionality. But you want to be able to say `:au_tas` and have it NOT pick up any `:au` holidays. I think this is a new feature (which …
> Remove :au_tas test for the time being

- kr.yaml
This fixes [Holidays #273](https://github.com/holidays/holidays/pull/273).  The test was just wrong!  View the correct information [on this Wikipedia article -- Midautumn Festival in 2016](https://en.wikipedia.org/wiki/List_of_public_holidays_in_South_Korea).
> Korean Thanksgiving is on September 15, not September 12 in 2016.  

- CHANGELOG.md
- fedex.yaml
I apparently missed this method when doing the v4.0.0 update! I
refactored the factories and didn't update it here. This has
been broken since the 4.0.0 major version bump.
> Fix fedex definition mistake in day_after_thanksgiving custom method

- ca.yaml
As talked about in this [issue](https://github.com/holidays/holidays/issues/240), I would like to propose that we correct some provincial rules regarding holidays in Canada. There are currently some holidays that shouldn't be nationwide, should be informal, etc. The affected holidays are:
- Easter Sunday
- Victoria Day
- Civic Holiday
- Thanksgiving
- Boxing Day
- [ca_ab](https://work.alberta.ca/employment-standards/general-holidays.html)
- [ca_bc](http://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/factsheets/statutory-holidays-in-bc-2015-2018)
- [ca_mb](https://www.gov.mb.ca/labour/standards/doc,gen-holidays-after-april-30-07,factsheet.html)
- [ca_nb](http://www2.gnb.ca/content/dam/gnb/Departments/petl-epft/PDF/es/FactSheets/PublicHolida …
> Correcting Canadian holidays as according to provincial rules

- ee.yaml
- Use small initial letters
- Good Friday and Easter Sunday aren't informal
- New Year's Day is always on January 1st
- Correct May Day definition
> Correct and enhance Estonian holiday definitions

- index.yaml
- mt_en.yaml
- mt_mt.yaml
Malta has two official languages: Maltese and English
- mt_mt.yaml offers holiday definitions in Maltese
- mt_en.yaml offers holiday definitions in English
- Tests are included
> Add Maltese holiday definitions

- au.yaml
Boxing Day is not observed in South Australia, Proclamation Day is observed instead on the same day.
https://en.wikipedia.org/wiki/Proclamation_Day
> Minor Localisation Issue

- .travis.yml
Ruby 2.1 is no more maintained.
See [detail](https://github.com/rvm/rvm/commit/03f468d4b6c31420e98e8d84db1a19b61a199f6b) .
> Remove ruby 2.1.0.

- ca.yaml
According to [this Alberta resource](http://work.alberta.ca/employment-standards/alberta-general-holidays.html) Heritage Day is treated as an informal holiday, much like Civic holiday in Ontario.
> Heritage Day in Alberta is informal

- kr.yaml
- Correct some existing holiday information
- Korean New Year's Day is for 3 days. (Last day of 12th lunar month / 1st day of 1st lunar month / 2nd day of 1st lunar month)
- Add some holidays (Korean Thanksgiving is for 3 days.) 
- Add a test case
- Change updated date
> Correct and enhance korean holiday definitions

- cl.yaml
Updates the following chilean holiday definitions:
- **St. Peter and St. Paul (San Pedro y San Pablo):** Since 2000 it is the nearest monday of 6/29
- **Columbus Day (Encuentro de dos mundos):** Since 2000 it is nearest monday of 10/12
- **Other Curches Day (Día de las Iglesias Evangélicas y Protestantes):** A new holiday since 2008 that works with the following logic: it is on the 10/31 unless it is on a tuesday which changes it to the friday before and if it lands on a wednesday, then is moved to the next friday.
The rules for all of these holidays is taken from: http://www.feriadoschilenos.cl (sorry it's in spanish)
> Update Chilean (CL) Holiday Definitions 

- ca.yaml
- lib/validation/test_validator.rb
I did an audit [already](https://github.com/holidays/definitions/pull/38), but was not careful the first time, so I missed some informal holidays. Here is another audit where I used the same external references to make holidays informal where necessary.
- [ca_ab](https://work.alberta.ca/employment-standards/general-holidays.html)
- [ca_bc](http://www2.gov.bc.ca/gov/content/employment-business/employment-standards-advice/employment-standards/factsheets/statutory-holidays-in-bc-2015-2018)
- [ca_mb](https://www.gov.mb.ca/labour/standards/doc,gen-holidays-after-april-30-07,factsheet.html)
- [ca_nb](http://www2.gnb.ca/content/dam/gnb/Departments/petl-epft/PDF/es/FactSheets/PublicHolidaysVacation.pdf)
- [ca_nl](http://www.cfib-fcei.ca/english/article/6421-paying-employees-for-public-holidays-nl. …
> Audit provincial holidays in Canada

- de.yaml
Reformation Day is only a state holiday in `de_bb`, `de_mv`, `de_sn`, `de_st` and `de_th`. This PR is going to correct that.
Included Changes:
* Correct definition for Reformation Day 
* Enhance tests
Related to issue https://github.com/holidays/definitions/issues/73
> Correct Reformation Day in German holiday definitions

- at.yaml
[Correct spelling](https://de.wikipedia.org/wiki/Unbefleckte_Empf%C3%A4ngnis#Mari.C3.A4_Empf.C3.A4ngnis_als_Hochfest_der_katholischen_Kirche)
> Fix typo for at defintion of 'Mariä Empfängnis'

- gb.yaml
Added relevant holidays for `je, gb_jsy, gg, gb_gsy`, using data from:
https://www.gov.je/Leisure/Events/WhatsOn/Pages/BankHolidayDates.aspx
https://www.gov.gg/article/120214/Public-and-school-holiday-dates
I have added tests - but it is not clear how to run these tests in the `definitions` repository.
> Added holidays for Jersey and Guernsey

- ca.yaml
- **Adding  'Family Day' for New Brunswick after 2018**  
http://www.gnb.ca/legis/bill/FILE/58/3/Bill-67-e.htm
On May 5, 2017, the New Brunswick government passed Bill 67, An Act Respecting Family Day that includes the introduction of a new statutory holiday – Family Day – to be recognized on the third Monday in February beginning in 2018. 
- **Adding 'National Aboriginal Day' for Yukon after 2017** 
http://www.gov.yk.ca/news/17-075.html
On May 8, 2017, Bill 2, the National Aboriginal Day Act received Royal Assent. The Bill amends the Employment Standards Act to create National Aboriginal Day as an annual statutory (public) holiday beginning on June 21, 2017. The CPA is pleased our recommendation to celebrate on the same day as the Northwest Territories was adopted.
> Updating holidays for Canada

- ar.yaml
Please read about [this PR](https://github.com/holidays/holidays/pull/307/files) .
links => https://www.officeholidays.com/countries/argentina/carnival.php
> changed carnival to easter related holidays for Argentine.

- jp.yaml
Japanese Emperor will change in 2019.
Dec 23rd is not holiday from 2019.
Instead, Feb 23rd is New Emperor's Birthday.
So there is no Emperor's birthday in 2019, the Japanese government will consider adding limited holiday on May 1st in 2019.
See detail https://github.com/holidays/definitions/issues/91 .
> Change Japanese Emperor's Birthday.

- de.yaml
The German "Reformation Day" has been added permanently as a new holiday in Bremen, Hamburg, Lower Saxony and Schleswig-Holstein, starting in 2018. See note "(9)" at https://en.wikipedia.org/wiki/Public_holidays_in_Germany
It'd be great if this could be added to the Holidays gem and released there before this holiday's first occurrence on 2018-10-31.
> German Reformation Day in four more states starting in 2018

- es.yaml
[La Mercè](https://en.wikipedia.org/wiki/La_Merc%C3%A8), official holiday in Catalunya, Spain
> adding La Mercè to official holidays in Catalunya, Spain

- CHANGELOG.md
- ch.yaml
- us.yaml
Based on changes submitted to generated definitions in https://github.com/holidays/holidays/pull/325
> Update Neujahrstag to apply to overall swiss region and bump to v3.1.0

- ca.yaml
https://en.wikipedia.org/wiki/Family_Day_(Canada)#British_Columbia
> On February 9, 2018, the British Columbia provincial government announced that Family Day would be moved to the 3rd Monday in February in 2019, to align their holiday with the rest of those provinces who observe it on that Monday.[15]
> Update Family Day date in CA BC

- federal_reserve_banks.yaml
- index.yaml
We've been relying on these definitions for when banks open.
holidays/definitions#87 broke this assumption since it changes it to when holidays are observed by the Board of Governors instead of when banks are open.
This seemed to simplest way to add a definition for purely banking holidays.
> Add definition for federal reserve holidays when banks are open.

- de.yaml
Berlin has just officially announced that the International Women's Day will be a public holiday from this year on, see https://www.berliner-zeitung.de/berlin/beschlossene-sache-der-8--maerz-ist-nun-offiziell-ein-berliner-feiertag-31927822 (in German).
As this is my first contribution, please check whether everything is correct, including the tests which I couldn't run.
> Add Berlin's new International Women's Day

- CHANGELOG.md
- federalreservebanks.yaml
I noticed that Friday 7/3/2020 was qualifying as an observed Federal Reserve Bank Holiday.  This should not qualify as a bank holiday:
> For holidays falling on Saturday, Federal Reserve Banks and Branches will be open the preceding Friday; however, the Board of Governors will be closed. For holidays falling on Sunday, all Federal Reserve offices will be closed the following Monday.
> https://www.federalreserve.gov/aboutthefed/k8.htm
The Federal Reserve Bank of Chicago rewords those bank rules here:
> Falls on a Saturday, not observed
> Falls on a Sunday, observed on Monday
> https://www.chicagofed.org/utilities/about-us/bank-holidays
I think this was [mistakenly changed here](https://github.com/holidays/definitions/pull/111/files#diff-c6f2fb254e9e3868507f472b3002198a).
I've updated the …
> Fix Federal Reserve Banks Observation of Independence Day

- ca.yaml
- us.yaml
Christmas is observed on nearest weekday rather than the next Monday if it falls on a weekend. I suspect some other definitions will need updating.
> Christmas is observed on nearest weekday

- ca.yaml
It seems that I missed a test when reviewing [this PR](https://github.com/holidays/definitions/pull/128). This also adds even more test coverage for Christmas Day for both observed and non-observed dates and removes an extra month key that is unnecessary.
> Update tests for Christmas Day in Canada (ca) region

- co.yaml
Correct colombia holiday.
See detail [this](https://github.com/holidays/definitions/commit/beba524a3331191a68af7d8c7a6f0a9c71ea46bf#diff-0d957262574f314a6d4f09cc55c48ee8)
> Correct colombia holiday.

- us.yaml
Addresses https://github.com/holidays/definitions/issues/134 by pulling in commits from https://github.com/tandahq/definitions.
Summary:
* Removes `Casimir Pulaski Day` from `:us_il` region since it is only celebrated in Chicago
* Remove `:us_il` from 'Election Day' regions
* Remove `:us_ca` from 'Emancipation Day' regions
cc @ghiculescu
> [issue-134] Fix issues with ':us' definitions

- CHANGELOG.md
- au.yaml
- ca.yaml
- cl.yaml
- de.yaml
- doc/SYNTAX.md
- doc/architecture/README.md
- doc/architecture/adr-002.md
- gb.yaml
- jp.yaml
- lib/validation/month_validator.rb
- ro.yaml
- spec/validation/month_validator_spec.rb
- tr.yaml
- ua.yaml
Addresses https://github.com/holidays/definitions/issues/117 and make updates to other `year_ranges` related behavior as listed below. This is a breaking change and will require a major semver bump. All consumers will be required to update to consume these latest definitions or they will see errors.
Renames the existing :year_ranges keys :before and :after to :until and :from, respectively. This is done so that the desired behavior of inclusivity is more clearly specified.
Example: a holiday should be valid up to and including 2002:
Old syntax - 'before: 2002'
New syntax - 'until: 2002
Currently we allow for multiple keys to be specified for each `:year_ranges` entry but we perform no validation that the selectors do not conflict with one another. This PR now validates that only a single …
> [issue-117] Update year_ranges for usage clarity

- .travis.yml
* Drop support for cruby 2.3
* Add support for cruby 2.6
* Update jruby-9.2.6.0
* Update to latest patch for all versions
* Allow failures for ruby-head and jruby-head
> Update supported Ruby versions

- it.yaml
Add Florence, Genoa, and Turin as IT regions observing Festa di San Giovanni Battista
https://www.officeholidays.com/holidays/italy/st-johns-day
> Add Festa di San Giovanni Battista

- gb.yaml
The UK government moved the may bank holiday to another day for the year 2020: 
https://www.gov.uk/government/news/2020-may-bank-holiday-will-be-moved-to-mark-75th-anniversary-of-ve-day
> Move May Day in 2020

- it.yaml
For each Venetian region of Italy (Venice `it_ve`, Verona `it_vr`, Vicenza `it_vi`, Padova `it_pd`, Treviso `it_tv`, Belluno `it_bl`, Rovigo `it_ro`) add pertinent patron's feast.
[[IT] Italian patron's feasts list by city ](https://it.wikipedia.org/wiki/Santi_patroni_cattolici_delle_citt%C3%A0_capoluogo_di_provincia_italiane)
> IT: Add venetian patron's feasts

- ca.yaml
See “The 2nd Monday in October (Thanksgiving)” listed on https://www.cnt.gouv.qc.ca/en/leaves-and-absences/statutory-holidays/index.html
> Add Québec to provinces observing Canadian Thanksgiving

- de.yaml
Signed-off-by: estani <estanislao.gonzalez@projo.zone>
I've also fixed an indentation complaint #147 
source:
"In Berlin wird der 75. Jahrestag am 8. Mai 2020 einmalig ein gesetzlicher Feiertag sein" (https://de.wikipedia.org/wiki/Tag_der_Befreiung)
law: https://www.berlin.de/sen/justiz/service/gesetze-und-verordnungen/2019/ausgabe-nr-3-vom-6-2-2019-s-21-32.pdf
> DE: adde new liberation day for Berlin 2020 only

- lu.yaml
Updated based on https://en.wikipedia.org/wiki/Public_holidays_in_Luxembourg
This addresses https://github.com/holidays/holidays/issues/288
> Add May 1 and May 9 holidays for Luxembourg

- tr.yaml
Hello everyone. I have updated Ramadan and Sacrifice holiday dates since they are shifting each year. 
There are many resources for validating these dates but most of them are Turkish. [This website](https://www.officeholidays.com/countries/turkey/2020) is appearing in the search result as a first item. You could check it or any other website for validation.
Please let me know if PR is against contribution rules. Thank you
> Add Ramadan & Sacrafice holidays in 2020

- mx.yaml
These dates are not formal holidays in mexico, at least for those who work.
> Mark mexicans dates as informal

- ca.yaml
Nunavut’s legislative assembly voted to pass Bill 29 making Nunavut Day, July 9, an officially statutory holiday across the territory.
More information available [here](https://nunatsiaq.com/stories/article/nunavut-day-is-now-a-statutory-holiday-in-the-territory/)
> Nunavut July 9th new statutory holiday from 2020

- federalreservebanks.yaml
Add 2024 calendar year to Federal Reserve banks
pulled from https://www.federalreserve.gov/aboutthefed/k8.htm - 2024 is the first year in a long time with all the fed holidays not falling on weekends.
> Add 2024 calendar year to Federal Reserve banks

- index.yaml
- ng.yaml
Hello everyone,
Adding the initial and minimum Nigerian holidays so Nigeria can be used in the gem. These holidays can be confirmed here: [Public Holidays in Nigeria - Wikipedia](https://en.wikipedia.org/wiki/Public_holidays_in_Nigeria).
Please let me know if I need to change anything or update anything, or if my PR is against contribution rules. I hope to include the Ramadan holidays in Nigeria next once this PR is accepted, so I am sure I am on the right track.
Cheers!
> Add Nigerian Holidays

- ca.yaml
According to Manitoba labor standards, Terry Fox Day is not a formal holiday. https://www.gov.mb.ca/labour/standards/doc,gen-holidays-after-april-30-07,factsheet.html#q13
@ttwo32  - could we please get some eyes on this asap - Thank you soo much
> Terry Fox Day not a formal holiday

- es.yaml
https://ajuntament.barcelona.cat/calendarifestius/es/
> add "Lunes de Pascua Granada" to Catalunya holidays

- gb.yaml
The observed public holiday in Northern Ireland for the 12th July,
"Battle of the Boyne", also called "Orangemen's Day", takes place
on the following Monday if it falls on the weekend.
From: https://www.nidirect.gov.uk/articles/bank-holidays
"When the usual date falls on a Saturday or Sunday, the
'substitute day' is normally the following Monday."
The examples given on the web page are:
Battle of the Boyne / Orangemen's Day, 13 July 2020, 12 July 2021
> Correcting observed Battle of the Boyne, N.Ireland (Problem occurs July 2020)

- jp.yaml
I have registered Japan's holidays in 2021.
The result created from this definition file is https://github.com/holidays/holidays/pull/373 for the https://github.com/holidays/holidays.
The correctness of the definition file is confirmed in the https://github.com/holidays/holidays/pull/373 to the holidays repository.
> Add 2021 jp holiday

- jp.yaml
Reflects the change of holidays announced by the Secretariat of the Tokyo Olympic Games and Tokyo Paralympic Games Promotion Office, Cabinet Secretariat on December 21, 2020.
see https://www.kantei.go.jp/jp/headline/tokyo2020/shukujitsu.html
Attached is a capture of the section from the above page where the holidays for 2021 are listed.
> :+1: Reflects changes in Japanese holidays in 2021

- za.yaml
All public holiday falling on a Sunday in South Africa(ZA), the Monday following on it shall be a public holiday.
https://www.gov.za/about-sa/public-holidays
> fix(za): Boxing day does not roll over to Monday if on Saturday

- au.yaml
Source: https://business.vic.gov.au/business-information/public-holidays/victorian-public-holidays-2021\#anzacday
> Do not roll over ANZAC day to Monday in au-vic

- ar.yaml
In Argentina there are holidays:
- that are portable to extend the weekend.
- that are created for tourist purposes.
Add new holiday _Paso a la Inmortalidad del General Martín Miguel de Güemes_
See [Feriados nacionales de la República Argentina en 2021](https://www.argentina.gob.ar/interior/feriados-nacionales-2021)
> Fix Argentina 2021 holidays

- us.yaml
[Juneteenth](https://en.wikipedia.org/wiki/Juneteenth) was recently made a federal holiday in the United States, so it's added here.
Emancipation Day in Texas is referring to the same holiday, but given that the official Juneteenth National Independence Day is now a federal holiday I left them separate. Let me know if I can make any changes, thanks!
> Add Juneteenth to US holidays

- ca.yaml
source: [Canada Introduces New Federal Holiday](https://mathewsdinsdale.com/canada-introduces-new-federal-holiday-national-day-for-truth-and-reconciliation/)
> Add Sept 30 new Canadian holiday

- ca.yaml
In late 2020, Ontario Canada decided that it would observe Christmas and Boxing Day in 2021 on Monday and Tuesday respectively instead of Friday and Monday. This patch adds this.
Also, a previous change (c246e83) changed Christmas to 'nearest weekday' without correcting the observed Boxing Day entries. This patch corrects that for other provinces.
> Update to Ontario Canada Christmas observed date and update to Boxing Day observed date

- federalreservebanks.yaml
Hi @ppeble , thanks for this awesome library! I've tried to follow the contributing guidelines and am happy to make changes if I've done this incorrectly.
This PR adds Juneteenth, [which is now a federal holiday](https://crsreports.congress.gov/product/pdf/IN/IN11697) to the :federalreservebanks region.
I've based it on [a similar one made for the :us region](https://github.com/holidays/definitions/pull/195).
> Add Juneteenth to `federalreservebanks` region

- gb.yaml
[Extra Bank Holiday to mark The Queen’s Platinum Jubilee in 2022](https://www.gov.uk/government/news/extra-bank-holiday-to-mark-the-queens-platinum-jubilee-in-2022). In addition, the Spring Bank Holiday has been moved to 2nd June for 2022 only.
See [GOV.UK Bank holidays](https://www.gov.uk/bank-holidays#england-and-wales) for an official reference.
> Add Platinum Jubilee bank holiday for 2022

- gb.yaml
since it is a significant sales holiday 3 weeks before easter https://en.wikipedia.org/wiki/Mothering_Sunday#Dates
> add informal Mothering Sunday in UK+IE

- federalreserve.yaml
- federalreservebanks.yaml
`federalreservebanks` region had a bug for Juneteenth holiday. It was using `to_weekday_if_weekend` instead of `to_monday_if_sunday`.
`federalreserve` region was missing Juneteenth holiday altogether.
> juneteenth for federalreserve and federalreservebanks

- doc/CONTRIBUTING.md
The testing instructions don't talk about how to test the integration between holiday and definitions. This updates the CONTRIBUTING doc to make sure it's easily discoverable by new contributors.
> Update contribution guideline testing instructions

- lv.yaml
Recently approved by Government of Latvia, to take place in July of 2023.
Hence, adding festival's end date to definition list.
> Add planned 2023 ocurrence of Latvian Song and Dance festival

- mx.yaml
In Mexico the holiday September 15 *Grito de Dolores* is an informal date, however it is marked as formal. You can see the formal dates  in the [government page for mexico](https://www.gob.mx/profedet/es/articulos/sabes-cuales-son-los-dias-de-descanso-obligatorios-163134?idiom=es).
> Update holiday september 15 in mexico as informal

- nz.yaml
NZ has a new holiday announced mid 2021. The dates are based on a lunar calendar and then shifted to Friday so calculation is impossible, but the next 30 years of them have been announced so hard coding is easy.
https://www.mbie.govt.nz/business-and-employment/employment-and-skills/employment-legislation-reviews/matariki/matariki-public-holiday/
> Add Matariki 2022-2052 to nz.yaml

- au.yaml
Closes #228 
The Wednesday that the Ekka holiday occurs on is dependent on the Friday that the RNA show period begins on, and that Friday changes depending on whether or not it's after August 5.
> Adds function to calculate shifting Ekka holiday

- ke.yaml
This indentation made the holidays file unparsable.
> Correct KE holidays indentation

- rs_cyrl.yaml
- rs_la.yaml
9th of May (dan pobede) is not a work free day. I didnt find any information on whether or not this should count as a holiday or not (also checked some other countries to see if there are similar occurences but I didnt find any) or what a holiday means in the context of this PR. If i made a mistake please say so.
How i percieved this repository is to allow developers to easily distinguish between working days and non working ones. Since 9th of May is not a work free day I propose to have it marked as an **informal** holiday. 
```
╰─➤  make …
```
> [rs] change 9th of May dan pobede to informal holiday

- ca.yaml
Context: We are using the holiday gem to manage holiday calendars and time-off calculations for international employees. It is important to us that the legally required holidays are accurately represented in each region, as well as the observed date.
National Truth and Reconciliation Day in Canada was created as a Federal holiday in 2021, but only for employees of the federal government.
Four regions recognize this as a statutory holiday for all workers: British Columbia, Northwest Territories, Prince Edward Island, and Yukon Territory.
Three regions recognize this as an optional holiday, at the employer's discretion: Alberta, Manitoba, Nunavut
Also, when it falls on a weekend it is observed the following monday.
https://canada-holidays.ca/
- you can drill down into each …
> Fix Truth and Reconciliation (Canada)- monday if weekend; stat in 4 regions, optional in 3

- au.yaml
Retire Family Day in ACT ([source](https://en.wikipedia.org/wiki/Family_Day))
> In 2018, Family and Community Day will no longer be a public holiday in the ACT. Replacing it is [Reconciliation Day](https://en.wikipedia.org/wiki/Reconciliation_Day), held on the first Monday on or after May 27.
Start Reconciliation Day in ACT ([source](https://en.wikipedia.org/wiki/National_Reconciliation_Week#:~:text=Reconciliation%20Day%20is%20a%20public,anniversary%20of%20the%201967%20referendum.))
> Reconciliation Day is a [public holiday](https://en.wikipedia.org/wiki/Public_holiday) in the [Australian Capital Territory](https://en.wikipedia.org/wiki/Australian_Capital_Territory) marking the start of National Reconciliation Week. It is held on the first Monday after or on 27 May, the anniversary of the …
> (au_act) retire family day, start reconiciliation day in au_act

- lv.yaml
Per subject. Tests pass.
- Ref: https://www.vestnesis.lv/op/2023/102A.1
- Ref: https://likumi.lv/ta/id/72608-par-svetku-atceres-un-atzimejamam-dienam
- Ref: https://saeima.lv/lv/aktualitates/saeimas-zinas/32316-29-maijs-bus-svetku-diena-lemj-saeima
> Add one-off public holiday in Latvia to honor ice hockey team bronze medal win in 2023 IIHF World Championship

- gb.yaml
On 8 May, there is a new Monday Bank holiday for the coronation of King Charles III
https://www.gov.uk/bank-holidays#england-and-wales
(There is already a may day holiday on 1 May)
> Update gb.yaml with Bank holiday for the coronation of King Charles III

- de.yaml
The `Internationaler Frauentag` in Germany beside Berlin is also a holiday in Mecklenburg-Vorpommern.
[German Wikipedia](https://de.wikipedia.org/wiki/Internationaler_Frauentag#Der_Frauentag_als_gesetzlicher_Feiertag)
> adds Intern. Women's Day holiday for Deutschland-Mecklenburg Vorpommern

- nz.yaml
👋 This PR includes updating a NZ holiday to reflect the monarch change in 2022.
Documentation for Queen's Birthday naming - https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/dates-for-previous-years/
Documentation for current King's Birthday naming - https://www.employment.govt.nz/leave-and-holidays/public-holidays/public-holidays-and-anniversary-dates/
> Update NZ Queen's Birthday to King's Birthday

- br.yaml
- doc/CONTRIBUTING.md
The 20th of November is now officially the "Dia Nacional de Zumbi e da Consciência Negra" (Black Consciousness) national holiday in Brazil.
Source:
"Diário Oficial da União" (Brazil's Federal Register) - https://www.in.gov.br/en/web/dou/-/lei-n-14.759-de-21-de-dezembro-de-2023-532716296
> [br] Adds black consciousness holiday

- de.yaml
This MR adds Weltkindertag in Germany for TH and its test.
> Fixes #246 add Weltkindertag in Germany for TH.

- gr.yml
`el` is the ISO 639 code for Greek language, but `gr` is the ISO 3166 code for Greece
> use correct country code gr for Greece

- au.yaml
Updating the name of the holidays from Queen to King.
In the WA region, the holiday has already been renamed to King in 2022, in other regions only in 2023.
Useful links:
https://publicholidays.com.au/kings-birthday/
https://www.commerce.wa.gov.au/labour-relations/previous-years-public-holiday-dates
> Update Australian Queen/King public holiday

- index.yaml
- tsx.yaml
The Toronto Stock Exchange (TSX) definitions are very close, but not quite to Canada's Ontario holidays. The only difference is that the TSX also observes Civic Holiday.
I have validated that these definitions match the dates provided on the [TSX's website](https://www.tsx.com/trading/calendars-and-trading-hours/calendar):
```
irb(main):035:0> Holidays.load_custom(File.expand_path('~/git/definitions/tsx.yaml')); nil
=> nil
irb(main):036:0> Holidays.between(Date.civil(2022, 1, 1), Date.civil(2022, 12, 31), :tsx, :observed).each { |h| puts h[:date].to_s + " => " + h[:name] }
2022-01-03 => New Year's Day
2022-02-21 => Family Day
2022-04-15 => Good Friday
2022-05-23 => Victoria Day
2022-07-01 => Canada Day
2022-08-01 => Civic Holiday
2022-09-05 => Labour Day
2022-10-10 => Thanksgiving …
```
> Add Toronto Stock Exchange (TSX) definitions

- il.yaml
Hi guys,
Just wanted to create at least some form of Israel holidays for the lib, Israel uses different type of calendar therefore can not be used in regular manner of holidays on X day of Y month. To solve it at least for some time Ive created holiday marks only for 4 upcoming years and will support it as soon as the dates are coming closer.
> Add Israel holidays ONLY for 2022-2026 years

- de.yaml
- Weltkindertag has been added as a new holiday for Thuringia (since 2019)
- Historical data for Heilige Drei Könige for Sachsen-Anhalt (since 1991)
- Historical data for Buß- und Bettag
- Historical data for Friedensfest (since 1950)
- Historical data for Tag der Arbeit (since 1933)
> Added Weltkindertag and some historical data
